oauth2:
  google:
    client-id: 883622715290-hlnj8g6snt2q8rhpeu114akt8p92l996.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

#    app 실행 후아래 주소를 주소창에 입력하면 accessToken을 받아와 구글 로그인 사용자 정보를 출력함
#    https://accounts.google.com/o/oauth2/auth?client_id=883622715290-hlnj8g6snt2q8rhpeu114akt8p92l996.apps.googleusercontent.com&redirect_uri=http://localhost:8080/login/oauth2/code/google&response_type=code&scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  kakao:
    client-id: 7455eac9bc76a0c055254eea8bc6bb38
    client-secret: DHS35DyFxEIepnFAJjzjUsXD6OX7Mc96
    redirect-uri: http://localhost:8080/login/oauth2/kakaocode/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me